import { Product } from '../interfaces/product';

export const MOCK_PRODUCTS: Product[] = [
    {
        id: 'nx-1001',
        name: 'Minimal Leather Backpack',
        brand: 'Nexora Studio',
        category: 'Fashion',
        price: 149,
        oldPrice: 189,
        rating: 4.7,
        reviewsCount: 312,
        stock: 27,
        status: 'In Stock',
        badge: 'Best Seller',
        images: [
            'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=1200&q=80',
        ],
        shortDescription: 'Premium leather backpack designed for everyday carry.',
        description: 'Crafted with a minimalist silhouette, blending durability with a clean urban aesthetic.',
        specs: [
            { label: 'Material', value: 'Genuine leather' },
            { label: 'Capacity', value: '18L' },
            { label: 'Laptop', value: 'Up to 15"' },
            { label: 'Weight', value: '1.1kg' },
        ],
    },
    {
        id: 'nx-1002',
        name: 'Smart Desk Lamp',
        brand: 'Nexora Home',
        category: 'Home',
        price: 79.99,
        rating: 4.5,
        reviewsCount: 145,
        stock: 61,
        status: 'In Stock',
        badge: 'Eco',
        images: [
            'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
        ],
        shortDescription: 'Warm lighting with focus modes for productivity.',
        description: 'A desk lamp with adaptive brightness modes, designed for long work sessions.',
        specs: [
            { label: 'Modes', value: 'Focus / Relax / Night' },
            { label: 'Power', value: 'USB-C' },
            { label: 'Brightness', value: 'Adjustable' },
            { label: 'Color temp', value: '2700K–5000K' },
        ],
    },
    {
        id: 'nx-1003',
        name: 'Noise-Cancelling Headphones',
        brand: 'Nexora Audio',
        category: 'Tech',
        price: 249.99,
        oldPrice: 299.99,
        rating: 4.8,
        reviewsCount: 892,
        stock: 14,
        status: 'Low Stock',
        badge: 'Limited',
        images: [
            'https://images.unsplash.com/photo-1518441902117-f0a4a0d3f9d8?auto=format&fit=crop&w=1200&q=80',
        ],
        shortDescription: 'Immersive sound with premium ANC.',
        description: 'Built for deep focus and travel. Powerful ANC, rich bass, crisp highs, and all-day comfort.',
        specs: [
            { label: 'Battery', value: '32 hours' },
            { label: 'ANC', value: 'Adaptive' },
            { label: 'Charging', value: 'USB-C fast charge' },
            { label: 'Codec', value: 'AAC / SBC' },
        ],
    },
    {
        id: 'nx-1004',
        name: 'Thermal Travel Bottle',
        brand: 'Nexora Outdoors',
        category: 'Accessories',
        price: 34.5,
        rating: 4.4,
        reviewsCount: 76,
        stock: 120,
        status: 'In Stock',
        badge: 'New',
        images: [
            'https://images.unsplash.com/photo-1526401485004-2fda9f6d6a0a?auto=format&fit=crop&w=1200&q=80',
        ],
        shortDescription: 'Keeps drinks cold or hot for hours.',
        description: 'Double-wall insulation keeps beverages cold for 18 hours and hot for 12 hours.',
        specs: [
            { label: 'Capacity', value: '600ml' },
            { label: 'Cold', value: '18 hours' },
            { label: 'Hot', value: '12 hours' },
            { label: 'Material', value: 'Stainless steel' },
        ],
    },
    {
        id: 'nx-1005',
        name: 'Wireless Charging Pad',
        brand: 'Nexora Tech',
        category: 'Tech',
        price: 39.99,
        rating: 4.3,
        reviewsCount: 210,
        stock: 80,
        status: 'In Stock',
        badge: 'Eco',
        images: [
            'https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=1200&q=80',
        ],
        shortDescription: 'Fast wireless charging with a clean minimalist surface.',
        description: 'Charge your phone and earbuds with a slim, grippy pad that looks great on any desk.',
    },
    {
        id: 'nx-1006',
        name: 'Linen Blend Throw Pillow',
        brand: 'Nexora Living',
        category: 'Home',
        price: 24.95,
        rating: 4.2,
        reviewsCount: 58,
        stock: 140,
        status: 'In Stock',
        badge: 'New',
        images: [
            'https://images.unsplash.com/photo-1582582494700-7b2f2c7c4b83?auto=format&fit=crop&w=1200&q=80',
        ],
        shortDescription: 'Textured linen comfort for sofas and beds.',
        description: 'Soft, breathable linen blend with premium stitching. Instantly elevates your space.',
    },
    {
        id: 'nx-1007',
        name: 'Minimal Key Organizer',
        brand: 'Nexora Essentials',
        category: 'Accessories',
        price: 19.9,
        rating: 4.6,
        reviewsCount: 344,
        stock: 200,
        status: 'In Stock',
        badge: 'Best Seller',
        images: [
            'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80',
        ],
        shortDescription: 'Silences key jingles and keeps everything tidy.',
        description: 'A slim organizer that holds up to 8 keys. Easy to use, built to last.',
    },
    {
        id: 'nx-1008',
        name: 'Modern Sunglasses',
        brand: 'Nexora Eyewear',
        category: 'Fashion',
        price: 59.0,
        oldPrice: 79.0,
        rating: 4.4,
        reviewsCount: 128,
        stock: 45,
        status: 'In Stock',
        badge: 'Limited',
        images: [
            'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1200&q=80',
        ],
        shortDescription: 'Polarized lenses with a premium matte finish.',
        description: 'Lightweight comfort and a sharp silhouette. Designed for everyday wear.',
    },
    {
        id: 'nx-1009',
        name: 'Ceramic Coffee Set',
        brand: 'Nexora Home',
        category: 'Home',
        price: 44.0,
        rating: 4.7,
        reviewsCount: 93,
        stock: 34,
        status: 'In Stock',
        badge: 'Eco',
        images: [
            'https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1200&q=80',
        ],
        shortDescription: 'Two cups + matching saucers in a clean matte glaze.',
        description: 'A minimalist coffee set that feels premium in hand and looks perfect on open shelves.',
    },
    {
        id: 'nx-1010',
        name: 'Everyday Tote Bag',
        brand: 'Nexora Studio',
        category: 'Fashion',
        price: 29.99,
        rating: 4.1,
        reviewsCount: 67,
        stock: 90,
        status: 'In Stock',
        badge: 'New',
        images: [
            'https://images.unsplash.com/photo-1520975693412-35a37f273463?auto=format&fit=crop&w=1200&q=80',
        ],
        shortDescription: 'Durable canvas tote for daily essentials.',
        description: 'Minimal look, strong handles, and roomy interior. Perfect for work or weekends.',
    },
];